<Project>
  <PropertyGroup>
    <Version>0.5.4-dev</Version>
    <OpenVisionLabProductVersion>0.5.4-dev</OpenVisionLabProductVersion>
    <OpenVisionLabViewerHostApiVersion>1.1</OpenVisionLabViewerHostApiVersion>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyMetadata Include="OpenVisionLabProductVersion" Value="$(OpenVisionLabProductVersion)" />
    <AssemblyMetadata Include="OpenVisionLabViewerHostApiVersion" Value="$(OpenVisionLabViewerHostApiVersion)" />
  </ItemGroup>
</Project>
