<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>OpenVisionLab.ThreeD.Reporting</RootNamespace>
    <AssemblyName>OpenVisionLab.ThreeD.Reporting</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenVisionLab.Integration.Contracts" Version="[0.1.0]" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenVisionLab.ThreeD.Core\OpenVisionLab.ThreeD.Core.csproj" />
    <ProjectReference Include="..\OpenVisionLab.ThreeD.Data\OpenVisionLab.ThreeD.Data.csproj" />
    <ProjectReference Include="..\OpenVisionLab.ThreeD.Tools\OpenVisionLab.ThreeD.Tools.csproj" />
  </ItemGroup>

</Project>
