using OpenVisionLab.ThreeD.Core;

namespace OpenVisionLab.ThreeD.Shell.ViewModels.Workbench;

internal static class ToolWorkbenchToolCatalog
{
    public static IReadOnlyList<ToolWorkbenchToolItem> Create() =>
    [
        new("Prepare", "Filter", "filter", 1, "HeightField", "FilteredHeightField", "Denoise the C3D raw-height source with the approved Median contract.", [new("Method", "Median"), new("KernelSize", "3"), new("MissingValuePolicy", "PreserveMask"), new("BoundaryPolicy", "AvailableNeighbors")]),
        new("Prepare", "Remove Outlier Pixels", "remove-outlier-pixels", 1, "HeightField", "FilteredHeightField", "Set isolated raw-height outliers missing when their local-median absolute deviation exceeds an explicit threshold. Original missing cells and source bytes stay unchanged.", [new("Rule", "LocalMedianAbsoluteDeviation"), new("WindowSize", "3"), new("MaximumAbsoluteDeviation", "25"), new("MinimumValidNeighbors", "3"), new("MissingValuePolicy", "PreserveMask"), new("BoundaryPolicy", "AvailableNeighbors"), new("OutlierPolicy", "SetMissing")]),
        new("Prepare", "Level Surface", "level-surface", 2, "Raw C3D HeightField + one or more GridRectangles", "LeveledHeightField + LevelingTransform", "Fit one plane across explicit reference ROIs and remove its X/Z raw-height trend without changing the source grid or missing mask.", [new("ReferenceFitPolicy", "LeastSquaresHeightPlane"), new("LevelingPolicy", "HeightDetrendToReferenceMean"), new("MissingValuePolicy", "PreserveMask"), new("GridPolicy", "PreserveSourceGrid"), new("MinimumValidSampleCount", "16"), new("MaximumReferenceRmsResidual", "5")]),
        new("Prepare", "ROI / Crop", "roi-crop", 1, "HeightField", "HeightField", "Restrict a later tool to an explicit source region.", [new("ROI", "Select in Viewer"), new("Output frame", "Keep source frame")]),
        new("Feature & Datum", "Height Difference Edge", "height-difference-edge", 1, "Published FilteredHeightField + GridRectangle", "EdgePointSet", "Extract one deterministic adjacent-height candidate per scanline in an explicit search band.", [new("ComparisonAxis", "AcrossColumns"), new("Polarity", "Rising"), new("MinimumDelta", "Set explicitly"), new("CandidatePolicy", "StrongestPerScanline"), new("PointPolicy", "PairMidpoint"), new("MissingValuePolicy", "SkipPair"), new("BoundaryPolicy", "WithinSelection")]),
        new("Feature & Datum", "2-Point Line", "two-point-line", 1, "Raw C3D HeightField + PointSet(2)", "LineFeature", "Construct a named ordered full-XYZ segment from two recipe-owned C3D grid picks.", [new("OutputRole", "Set explicitly"), new("ConstructionPolicy", "OrderedPointsDefineSegment")]),
        new("Feature & Datum", "3-Point Plane", "three-point-plane", 2, "Raw C3D HeightField + PointSet(3)", "PlaneFeature", "Construct a named ordered full-XYZ datum plane from three recipe-owned C3D grid picks.", [new("OutputRole", "Set explicitly"), new("ConstructionPolicy", "OrderedPointsDefineOrientedPlane")]),
        new("Measure", "Datum Plane Raw-Height Deviation", "datum-plane-raw-height-deviation", 2, "Raw C3D HeightField + Published PlaneFeature + GridRectangle", "DatumPlaneDeviationResult", "Measure raw-height residual P2V against one published manual datum plane without changing or re-gridding the source C3D.", [new("MaximumPeakToValleyRawHeight", "Set explicitly"), new("OutputRole", "Set explicitly"), new("ResidualPolicy", "RawHeightMinusDatumPlanePredictedRawHeight"), new("MinimumValidSampleCount", "3"), new("MinimumAbsoluteNormalY", "0.1")]),
        new("Feature & Datum", "3D Line Fit", "three-d-line-fit", 1, "Published EdgePointSet", "LineFeature", "Fit one deterministic full-XYZ line to an explicit published edge-point entity.", [new("FitMethod", "DeterministicConsensusOrthogonalTls"), new("MaximumOrthogonalResidual", "Set explicitly"), new("MinimumInlierCount", "Set explicitly"), new("MinimumInlierRatio", "Set explicitly"), new("MinimumInlierScanlineSpan", "Set explicitly"), new("HypothesisPolicy", "Sha256PairSchedule"), new("MaximumHypotheses", "256"), new("RefinementPolicy", "OrthogonalTlsUntilStable10"), new("DirectionPolicy", "PositiveScanlineAxis"), new("EndpointPolicy", "InlierProjectionExtents")]),
        new("Feature & Datum", "Line Intersection", "line-intersection", 2, "Published LineFeature + LineFeature", "CornerAnchor", "Create a corner anchor only after full-XYZ closest-approach, angle, and bounded-support gates pass.", [new("MaximumClosestApproachDistance", "Set explicitly"), new("MinimumAcuteAngleDegrees", "Set explicitly"), new("MaximumSupportExtension", "Set explicitly"), new("OutputRole", "Set explicitly"), new("ClosestApproachPolicy", "MidpointOfClosestPoints"), new("ParallelPolicy", "RejectBelowMinimumAcuteAngle"), new("SupportPolicy", "WithinInlierProjectionExtentsWithMaximumExtension")]),
        new("Feature & Datum", "Landmark Correspondence", "landmark-correspondence", 1, "Correspondence selection", "CorrespondenceSet", "Validate four named Published CornerAnchors against explicit reference coordinates before a later transform.", [new("PairCountPolicy", "ExactlyFour"), new("SourceArtifactPolicy", "CurrentPublishedCornerAnchor"), new("AffineIndependencePolicy", "RequireNonDegenerateTetrahedra")]),
        new("Transform", "XYZ Affine Solve", "xyz-affine-solve", 1, "Published CorrespondenceSet", "AffineTransform3D", "Solve one full XYZ source-to-reference matrix from exactly four published correspondence pairs. It does not move C3D points.", [new("SolvePolicy", "ExactFourPartialPivot"), new("MaximumConditionEstimate", "1000000"), new("ArithmeticResidualWarning", "0.001")]),
        new("Transform", "Apply XYZ Affine", "xyz-affine-apply", 2, "Verified raw C3D + Published AffineTransform3D", "TransformedPointCloud", "Transform each finite raw source-grid point once in full XYZ while preserving its row/column locator. It does not re-grid, interpolate, triangulate, or measure.", []),
        new("Transform", "Re-grid Height Map", "re-grid-height-map", 1, "Published TransformedPointCloud", "TransformedHeightField", "Project a published full-XYZ cloud into one explicit right-handed reference grid. Missing cells remain missing; Preview rejects out-of-bounds points and Publish requires authored coverage.", CreateDefaultRegridParameters()),
        new("Measure", "Thickness", "thickness", 3, "HeightField + Reference GridRectangle + Measurement GridRectangle", "MeasurementResult", "Fit a reference surface, then measure signed H-axis separation across a second recipe-owned ROI. Preview remains explicit.", [new("MinimumThickness", "0"), new("MaximumThickness", "100000"), new("MinimumValidSampleCount", "1")]),
        new("Measure", "Warpage", "warpage", 2, "HeightField + GridRectangle", "MeasurementResult", "Measure best-fit-plane residual warpage inside one recipe-owned grid ROI. This is one reusable measurement tool, not a product mode.", [new("MaximumPeakToValley", "100000"), new("MaximumRms", "100000"), new("MinimumValidSampleCount", "3")]),
        new("Measure", "Plane Flatness", "plane-flatness", 3, "TransformedHeightField + Reference GridRectangle + Measurement GridRectangle", "MeasurementResult", "Fit a reference plane in one artifact-owned ROI and measure signed-distance flatness in a second ROI. Preview and Publish remain explicit.", [new("MaximumFlatness", "100000"), new("MinimumReferenceSampleCount", "3"), new("MinimumMeasurementSampleCount", "3")]),
        new("Measure", "Point Pair Dimensions", "point-pair-dimensions", 2, "TransformedHeightField + PointSet(2)", "MeasurementResult", "Measure full-XYZ distance, reference-plane width, height-axis delta, and elevation angle between two ordered artifact-owned picks.", [new("ExpectedDistance", "0"), new("DistanceTolerance", "100000"), new("ExpectedPlanarWidth", "0"), new("PlanarWidthTolerance", "100000"), new("ExpectedElevationAngleDegrees", "0"), new("ElevationAngleToleranceDegrees", "90")]),
        new("Measure", "Gap / Flush", "gap-flush", 3, "TransformedHeightField + First GridRectangle + Second GridRectangle", "MeasurementResult", "Measure signed U-axis separation between facing ROI edges and signed H-axis mean-height difference. ROI order defines the sign; Preview and Publish remain explicit.", [new("ExpectedGap", "0"), new("GapTolerance", "100000"), new("ExpectedFlush", "0"), new("FlushTolerance", "100000")]),
        new("Measure", "Volume", "volume", 3, "TransformedHeightField + Reference GridRectangle + Measurement GridRectangle", "MeasurementResult", "Fit an A3 reference-plane ROI and integrate signed H-axis height over a second ROI. Values remain in the declared reference-grid model unit cubed; Preview and Publish remain explicit.", [new("ExpectedNetVolume", "0"), new("VolumeTolerance", "100000")]),
        new("Measure", "Cross-section Dimensions", "cross-section-dimensions", 2, "TransformedHeightField + one-row GridRectangle", "MeasurementResult", "Measure U-axis width and H-axis range along one explicitly authored A3 row segment. Preview and Publish remain explicit.", [new("ExpectedWidth", "0"), new("WidthTolerance", "100000"), new("ExpectedHeightRange", "0"), new("HeightTolerance", "100000")]),
        new("Measure", "Completeness Grid", "completeness-grid", 3, "HeightField + Reference GridRectangle + Inspection GridRectangle", "CompletenessGridMetrics", "Generate deterministic native-grid cells, apply inclusive finite-coverage and reference-relative height limits, then publish cell and aggregate Pass/Fail evidence.", [new("Rows", "2"), new("Columns", "2"), new("XPitchColumns", "2"), new("ZPitchRows", "2"), new("CellWidthColumns", "2"), new("CellHeightRows", "2"), new("CellShape", "GridRectangle"), new("MinimumFiniteCoverageRatio", "0.95"), new("MinimumReferenceRelativeMeanRawHeight", "-100000"), new("MaximumReferenceRelativeMeanRawHeight", "100000")]),
        new("Review", "Overlay / Control Review", "overlay-control-review", 1, "MeasurementResult", "ReviewOverlay", "Group overlays, controls, acceptance, and run evidence without changing the source.", [new("Overlay", "Selected results"), new("Publish", "Explicit")])
    ];

    private static IReadOnlyList<ToolWorkbenchParameterSeed> CreateDefaultRegridParameters() =>
        C3DReferenceGridProfile.Create(
            "frame.reference", "unitless", "Authored reference grid", "R1",
            new C3DReferenceGridVector(0, 0, 0),
            new C3DReferenceGridVector(1, 0, 0),
            new C3DReferenceGridVector(0, 1, 0),
            new C3DReferenceGridVector(0, 0, 1),
            1, 1, 1, 1, 1)
        .ToRecipeParameters()
        .Select(parameter => new ToolWorkbenchParameterSeed(parameter.Name, parameter.Value))
        .ToArray();
}
