using System.Globalization;
using System.ComponentModel;
using OpenVisionLab;
using OpenVisionLab.ThreeD.Viewer.Hosting;

namespace OpenVisionLab.ThreeD.Viewer.Localization;

public sealed class ViewerLocalization : INotifyPropertyChanged, IViewerLocalizationProvider
{
    private static readonly (string English, string Korean)[] RuntimeReplacements =
    [
        ("generated cube and point cloud loaded", "생성된 큐브와 포인트 클라우드 로드됨"),
        ("recipe comparison matched", "레시피 비교 일치"),
        ("recipe comparison pending", "레시피 비교 대기"),
        ("Runner/UI contract matched", "Runner/UI 계약 일치"),
        ("C3D Height Deviation Rule", "C3D 높이 편차 규칙"),
        ("Balanced: up to", "균형: 최대"),
        ("Detailed: up to", "상세: 최대"),
        ("Fast: up to", "빠름: 최대"),
        ("Model SHA-256: ", "모델 SHA-256: "),
        ("Scene SHA-256: ", "장면 SHA-256: "),
        ("Pose SHA-256: ", "포즈 SHA-256: "),
        ("Overlay SHA-256: ", "오버레이 SHA-256: "),
        ("Execution SHA-256: ", "실행 SHA-256: "),
        ("Policy SHA-256: ", "정책 SHA-256: "),
        ("Assessment SHA-256: ", "평가 SHA-256: "),
        ("Model edge SHA-256: ", "모델 에지 SHA-256: "),
        ("Scene edge SHA-256: ", "장면 에지 SHA-256: "),
        ("Surface/edge score SHA-256: ", "표면/에지 점수 SHA-256: "),
        ("Edge diagnostic overlay SHA-256: ", "에지 진단 오버레이 SHA-256: "),
        ("Acquisition orientation SHA-256: ", "취득 방향 SHA-256: "),
        ("Independent surface/edge assessment SHA-256: ", "독립 표면/에지 평가 SHA-256: "),
        ("False-positive review SHA-256: ", "오검출 검토 SHA-256: "),
        ("Runtime is observational and excluded from deterministic identities.", "실행은 관찰용이며 결정적 식별자에서 제외됩니다."),
        ("No surface-match evidence.", "표면 매칭 증거 없음."),
        ("Height color range: not loaded", "높이 색상 범위: 로드되지 않음"),
        ("Height color range ", "높이 색상 범위 "),
        (" raw-height · ", " 원시 높이 · "),
        (" · Auto · ", " · 자동 · "),
        (" · Manual · ", " · 수동 · "),
        (" · view only", " · 표시 전용"),
        ("C3D Plane Flatness", "C3D 평면 평탄도"),
        ("C3D Point Pair Dimensions", "C3D 포인트 쌍 치수"),
        ("C3D Thickness ROI", "C3D 두께 ROI"),
        ("C3D Thickness", "C3D 두께"),
        ("C3D Gap / Flush", "C3D 갭 / 플러시"),
        ("C3D Volume", "C3D 체적"),
        ("C3D Cross-section Dimensions", "C3D 단면 치수"),
        ("C3D Warpage ROI", "C3D 워페이지 ROI"),
        ("C3D Warpage", "C3D 워페이지"),
        ("C3D Height Profile", "C3D 높이 프로파일"),
        ("C3D Alignment", "C3D 정렬"),
        ("Plane Distance Measurement", "평면 거리 측정"),
        ("Height Difference Edge Point", "높이 차이 에지 포인트"),
        ("3D Line Fit point", "3D 선 피팅 포인트"),
        ("Nominal / Actual Deviation Point", "기준 / 실제 편차 포인트"),
        ("Nominal / Actual Surface Deviation", "기준 / 실제 표면 편차"),
        ("TransformedHeightField Teaching Selection Candidate", "변환 높이 필드 티칭 선택 후보"),
        ("Teaching Selection Candidate", "티칭 선택 후보"),
        ("Selected 3D Box ROI: ", "선택된 3D 박스 ROI: "),
        ("Selected Surface ROI: ", "선택된 표면 ROI: "),
        ("Public GLB Mesh", "공개 GLB 메시"),
        ("Public LAZ/LAS Metadata", "공개 LAZ/LAS 메타데이터"),
        ("Public LAZ/LAS Point Cloud", "공개 LAZ/LAS 포인트 클라우드"),
        ("Generated Point Cloud", "생성된 포인트 클라우드"),
        ("C3D Height Grid", "C3D 높이 그리드"),
        (" Mesh: ", " 메시: "),
        ("Result Overlay", "결과 오버레이"),
        ("Box ROI", "박스 ROI"),
        ("ROI Step Compare", "ROI 단계 비교"),
        ("Section Plane", "단면 평면"),
        ("Two Point Measurement", "2-포인트 측정"),
        ("STL Mesh", "STL 메시"),
        ("(not picked)", "(선택되지 않음)"),
        ("(load failed)", "(로드 실패)"),
        ("(metadata only)", "(메타데이터만)"),
        ("(sampled points)", "(샘플 포인트)"),
        ("(viewer-only sample)", "(뷰어 전용 샘플)"),
        ("(sample-backed rule)", "(샘플 기반 규칙)"),
        ("(invalid reference ROI)", "(잘못된 참조 ROI)"),
        ("midpoint (", "중점 ("),
        ("ACCEPTED  Surface ", "허용됨  표면 "),
        ("REJECTED  Surface ", "거부됨  표면 "),
        (" · Edge ", " · 에지 "),
        ("Accepted reference unavailable", "허용된 참조 사용 불가"),
        ("Rejected candidate unavailable", "거부된 후보 사용 불가"),
        ("Original scenes + samples retained · ", "원본 장면 + 샘플 유지됨 · "),
        ("Review evidence unavailable", "검토 증거 사용 불가"),
        ("Current display:", "현재 표시:"),
        ("Below: ", "하한 미만: "),
        ("Within: ", "허용오차 이내: "),
        ("Above: ", "상한 초과: "),
        ("display ", "표시 "),
        ("Deviation distribution: not available", "편차 분포: 사용 불가"),
        ("Next Preview:", "다음 미리보기:"),
        ("run Preview to apply", "적용하려면 미리보기를 실행하세요"),
        ("matches current display", "현재 표시와 동일"),
        ("points", "포인트"),
        ("stride", "간격"),
        ("budget", "예산"),
        ("C3D points", "C3D 포인트"),
        ("LAZ/LAS points", "LAZ/LAS 포인트"),
        ("LAZ/LAS loading", "LAZ/LAS 불러오는 중"),
        ("LAZ/LAS loaded", "LAZ/LAS 불러오기 완료"),
        ("LAZ/LAS sample reused", "LAZ/LAS 샘플 재사용"),
        ("LAZ/LAS load cancelled", "LAZ/LAS 불러오기 취소됨"),
        ("LAZ/LAS load failed", "LAZ/LAS 불러오기 실패"),
        ("current point cloud retained", "현재 포인트 클라우드 유지됨"),
        ("mesh triangles", "메시 삼각형"),
        ("UI metric:", "UI 측정값:"),
        ("Runner metric:", "Runner 측정값:"),
        ("Key metric:", "핵심 측정값:"),
        ("Recipe steps:", "레시피 단계:"),
        ("Status: Inputs ready | invalid tolerance", "상태: 입력 준비됨 | 잘못된 허용오차"),
        ("Status: Inputs ready", "상태: 입력 준비됨"),
        ("Status: Preview stale", "상태: 미리보기 갱신 필요"),
        ("Status: Preview running", "상태: 미리보기 실행 중"),
        ("Status: Preview ready", "상태: 미리보기 준비됨"),
        ("Status: Published", "상태: 게시됨"),
        ("Status: Failed", "상태: 실패"),
        ("Status: Unknown", "상태: 알 수 없음"),
        ("Status: Pass", "상태: 통과"),
        ("Status: Fail", "상태: 실패"),
        ("Status: Error", "상태: 오류"),
        ("Evidence: Matched", "증거: 일치"),
        ("Evidence: Pending", "증거: 대기"),
        ("Status:", "상태:"),
        ("Evidence:", "증거:"),
        ("Viewer:", "뷰어:"),
        ("Compare:", "비교:"),
        ("Runner:", "Runner:"),
        ("UI:", "UI:"),
        ("Shell:", "셸:"),
        ("JSON:", "JSON:"),
        ("HTML:", "HTML:"),
        ("CSV:", "CSV:"),
        ("Report:", "보고서:"),
        ("Run:", "실행:"),
        (" / Fail", " / 실패"),
        (" | Fail", " | 실패"),
        (" | Matched", " | 일치"),
        (" | Pending", " | 대기"),
        ("current C3D height deviation", "현재 C3D 높이 편차"),
        ("Surface Deviation", "표면 편차"),
        ("Actual to Nominal", "실제 → 기준"),
        ("Generated Unit Cube", "생성된 단위 큐브"),
        ("C3D Thickness Sample", "C3D 두께 샘플"),
        ("No comparison evidence.", "비교 증거 없음"),
        ("Source/result separation:", "소스/결과 분리:"),
        ("Fitted segment and direction", "피팅 선분 및 방향"),
        ("Closest-approach connector", "최근접 연결선"),
        ("Point pair dimensions", "포인트 쌍 치수"),
        ("point cloud", "포인트 클라우드"),
        ("height grid", "높이 그리드"),
        ("height delta", "높이 차이"),
        ("two-point", "2-포인트"),
        ("Cross-section Dimensions", "단면 치수"),
        ("waiting for first frame", "첫 프레임 대기 중"),
        ("Right-handed", "오른손 좌표계"),
        ("Y-up height", "Y축 높이"),
        ("raw-height retained", "원시 높이 유지"),
        ("source = aligned", "소스 = 정렬"),
        ("source frame", "소스 좌표계"),
        ("source only", "소스만"),
        ("not available", "사용할 수 없음"),
        ("not aligned", "미정렬"),
        ("not applied", "미적용"),
        ("not loaded", "로드되지 않음"),
        ("not set", "미설정"),
        ("unavailable", "사용할 수 없음"),
        ("mode pending", "모드 준비 중"),
        ("Diagnostic channel", "진단 채널"),
        ("No selectable source diagnostic channel", "선택 가능한 소스 진단 채널 없음"),
        ("Display only", "표시 전용"),
        ("Source channel is available", "소스 채널 사용 가능"),
        ("Intensity", "강도"),
        ("Color", "색상"),
        ("Depth", "깊이"),
        ("Normal", "노멀"),
        ("Confidence", "신뢰도"),
        ("Signal/Noise", "신호/잡음"),
        ("Inlier", "인라이어"),
        ("Outlier", "아웃라이어"),
        ("Source & references", "소스 및 참조"),
        ("Recipe pipeline", "레시피 파이프라인"),
        ("Teaching selections", "티칭 선택 영역"),
        ("Ordered, read-first INPUT → OUTPUT teaching structure.", "순서 기반 읽기 우선 INPUT → OUTPUT 티칭 구조."),
        ("Unresolved input entity ID.", "해결되지 않은 입력 엔터티 ID입니다."),
        ("Recipe-owned source-bound captures.", "레시피가 소유한 소스 바운드 캡처."),
        ("preview not run", "미리보기 미실행"),
        ("visible", "표시"),
        ("hidden", "숨김"),
        ("updated", "갱신됨"),
        ("requires", "필요:"),
        ("failed:", "실패:"),
        ("cancelled", "취소됨"),
        ("retained", "유지됨"),
        ("Model units:", "모델 단위:"),
        ("Camera:", "카메라:"),
        ("Performance:", "성능:"),
        ("Transform:", "변환:"),
        ("ROI alignment:", "ROI 정렬:"),
        ("Alignment:", "정렬:"),
        ("Mapping:", "매핑:"),
        ("Selection mode:", "선택 모드:"),
        ("Render density:", "렌더 밀도:"),
        ("Point size:", "포인트 크기:"),
        ("Viewer hosted", "뷰어 연결됨"),
        ("Cube width:", "큐브 너비:"),
        ("Expected center:", "예상 중심:"),
        ("Validation query:", "검증 쿼리:"),
        ("Validation warning:", "검증 경고:"),
        ("Validation:", "검증:"),
        ("Inputs and frame:", "입력 및 프레임:"),
        ("Actual and nominal inputs are required.", "실제 및 기준 입력이 필요합니다."),
        ("Comparing actual to nominal", "실제와 기준 비교"),
        ("Full query:", "전체 쿼리:"),
        ("Preview failed:", "미리보기 실패:"),
        ("Signed deviation result:", "부호 있는 편차 결과:"),
        ("Signed range", "부호 있는 범위"),
        ("full-query metrics", "전체 쿼리 측정값"),
        ("signed ", "부호 있는 "),
        ("unsigned ", "절대값 "),
        ("nearest nominal triangle #", "가장 가까운 기준 삼각형 #"),
        ("robust", "강건"),
        ("direct", "직접"),
        ("sign ", "부호 "),
        ("actual=", "실제="),
        ("query=", "쿼리="),
        ("Actual:", "실제:"),
        ("Nominal:", "기준:"),
        ("Frame:", "좌표계:"),
        ("Units:", "단위:"),
        ("Recipe:", "레시피:"),
        ("Source:", "소스:"),
        ("UI contract:", "UI 계약:"),
        ("Runner report:", "Runner 보고서:"),
        ("Run Record:", "실행 기록:"),
        ("Tolerance: none", "허용오차: 없음"),
        ("Tolerance:", "허용오차:"),
        ("Published result:", "게시 결과:"),
        ("Ready:", "준비:"),
        ("Direction:", "방향:"),
        ("No inputs", "입력 없음"),
        ("Progress:", "진행:"),
        ("No comparison preview.", "비교 미리보기 없음."),
        ("Selected point:", "선택 지점:"),
        ("Query point #", "쿼리 포인트 #"),
        ("Below lower tolerance", "하한 허용오차 미만"),
        ("Above upper tolerance", "상한 허용오차 초과"),
        ("Within tolerance", "허용오차 이내"),
        ("ROI edit:", "ROI 편집:"),
        ("click right ROI center to finish comparison.", "비교를 마치려면 오른쪽 ROI 중심을 클릭하세요."),
        ("interactive L/R centers selected; click again to start a new pair.", "대화형 L/R 중심 선택됨; 새 쌍을 시작하려면 다시 클릭하세요."),
        ("auto regions; click left ROI then right ROI.", "자동 영역; 왼쪽 ROI, 오른쪽 ROI 순서로 클릭하세요."),
        ("Selection overlay hidden", "선택 오버레이 숨김"),
        ("Load or relink a C3D source to begin teaching.", "티칭을 시작하려면 C3D 소스를 불러오거나 다시 연결하세요."),
        ("Point selection:", "포인트 선택:"),
        ("Mesh selection:", "메시 선택:"),
        ("Cube pick:", "큐브 선택:"),
        ("LAZ/LAS point:", "LAZ/LAS 포인트:"),
        ("LAZ/LAS metadata loaded", "LAZ/LAS 메타데이터 로드됨"),
        ("sampled point cloud", "샘플링된 포인트 클라우드"),
        ("generated point cloud peak", "생성된 포인트 클라우드 최고점"),
        ("viewer state only", "뷰어 상태 전용"),
        ("Section plane:", "단면 평면:"),
        ("profile not loaded", "프로파일 로드되지 않음"),
        ("Profile: ", "프로파일: "),
        ("P1-P2 profile", "P1-P2 프로파일"),
        ("Two-point:", "2-포인트:"),
        ("Output policy: enabled", "출력 정책: 사용"),
        ("Output policy: disabled; Preview, Publish, and Run create no output artifact", "출력 정책: 비활성; 미리보기, 게시, 실행은 출력 산출물을 만들지 않음"),
        ("Recipe loaded:", "레시피 로드됨:"),
        ("Recipe saved:", "레시피 저장됨:"),
        ("editable", "편집 가능"),
        ("Result overlay hidden", "결과 오버레이 숨김"),
        ("Preview:", "미리보기:"),
        ("Measurement overlay hidden", "측정 오버레이 숨김"),
        ("Missing sample:", "샘플 없음:"),
        ("Missing LAZ/LAS sample:", "LAZ/LAS 샘플 없음:"),
        ("Unsupported or corrupt LAZ/LAS point decode:", "지원되지 않거나 손상된 LAZ/LAS 포인트 디코드:"),
        ("Unsupported or corrupt LAZ/LAS:", "지원되지 않거나 손상된 LAZ/LAS:"),
        (" | valid ", " | 유효 "),
        (" | zero ", " | 0값 "),
        ("Missing GLB sample:", "GLB 샘플 없음:"),
        ("Missing STL sample:", "STL 샘플 없음:"),
        ("Unsupported or corrupt GLB:", "지원되지 않거나 손상된 GLB:"),
        ("Unsupported or corrupt STL:", "지원되지 않거나 손상된 STL:"),
        ("vertex colors none", "정점 색상 없음"),
        ("vertex colors ", "정점 색상 "),
        ("bytes | texcoords ", "바이트 | 텍스처 좌표 "),
        ("texture none", "텍스처 없음"),
        ("texture ", "텍스처 "),
        ("normal evidence ", "노멀 증거 "),
        ("normals unavailable", "노멀 사용 불가"),
        ("normals ", "노멀 "),
        ("format ", "형식 "),
        ("vertices ", "정점 "),
        ("triangles ", "삼각형 "),
        ("bounds ", "경계 "),
        (") to (", ") ~ ("),
        ("C3D sample loaded; no measurement tool published", "C3D 샘플 로드됨; 게시된 측정 도구 없음"),
        ("No recipe source is ready.", "레시피 소스가 준비되지 않음."),
        (" mesh loaded; measurement tools pending", " 메시 로드됨; 측정 도구 준비 중"),
        ("LAZ header loaded; compressed point records not decoded yet", "LAZ 헤더 로드됨; 압축 포인트 레코드는 아직 디코드되지 않음"),
        ("LAZ/LAS point decode loaded; XYZ/RGB sampled points rendered.", "LAZ/LAS 포인트 디코드 로드됨; XYZ/RGB 샘플 포인트 렌더링됨."),
        ("Distance and height delta: reset after point-cloud density change", "포인트 클라우드 밀도 변경 후 거리 및 높이 차이 초기화됨"),
        ("Inputs validated; explicit Preview requested.", "입력 검증됨; 명시적 미리보기 요청됨."),
        ("Pick P2 to measure distance and height delta.", "거리와 높이 차이를 측정하려면 P2를 선택하세요."),
        ("Distance and height delta: pending", "거리 및 높이 차이: 대기"),
        ("point pick:", "포인트 선택:"),
        (" pick:", " 선택:"),
        ("No published result: output disabled", "게시된 결과 없음: 출력 비활성"),
        ("Metric:", "측정값:"),
        ("Overlays:", "오버레이:"),
        ("Layer: published result", "레이어: 게시 결과"),
        ("Height map:", "높이 맵:"),
        ("Range:", "범위:"),
        (" | rendered ", " | 렌더링 "),
        ("min ", "최소 "),
        ("max ", "최대 "),
        ("mean ", "평균 "),
        ("LAZ/LAS sampling:", "LAZ/LAS 샘플링:"),
        ("LAZ/LAS acceptance: pending", "LAZ/LAS 판정: 대기"),
        ("LAZ/LAS acceptance: Pass", "LAZ/LAS 판정: 통과"),
        ("LAZ/LAS acceptance: Fail", "LAZ/LAS 판정: 실패"),
        ("LAZ/LAS acceptance:", "LAZ/LAS 판정:"),
        (" | load ", " | 로드 "),
        (" | decoded ", " | 디코드 "),
        (" | sampled ", " | 샘플링 "),
        (" | stride ", " | 간격 "),
        (" | density ", " | 밀도 "),
        (" | sample ", " | 샘플 "),
        ("bounds match ", "경계 일치 "),
        ("compressed ", "압축 "),
        ("metadata only; point rendering pending", "메타데이터만; 포인트 렌더링 대기"),
        ("Source entities:", "소스 엔터티:"),
        ("Source layers:", "소스 레이어:"),
        ("Visible source layers:", "표시 소스 레이어:"),
        ("Preview layers:", "미리보기 레이어:"),
        ("Published results:", "게시 결과:"),
        ("source -> aligned display coordinates", "소스 -> 정렬 표시 좌표"),
        ("no source", "소스 없음"),
        ("LAZ/LAS metadata hidden", "LAZ/LAS 메타데이터 숨김"),
        ("Raw unavailable", "원시 결과 사용 불가"),
        ("Raw Matched", "원시 일치"),
        ("Raw NoMatch", "원시 불일치"),
        ("Surface and 3D-edge evidence meet their independent limits", "표면 및 3D 엣지 증거가 각각의 한계를 충족함"),
        ("Surface coverage is below its authored minimum", "표면 커버리지가 설정된 최소값보다 낮음"),
        ("Surface RMSE is unavailable", "표면 RMSE를 사용할 수 없음"),
        ("Surface RMSE exceeds its authored maximum", "표면 RMSE가 설정된 최대값을 초과함"),
        ("3D-edge coverage exposes a surface-only false positive", "3D 엣지 커버리지가 표면 전용 오검출을 드러냄"),
        ("3D-edge RMSE is unavailable", "3D 엣지 RMSE를 사용할 수 없음"),
        ("3D-edge RMSE exceeds its authored maximum", "3D 엣지 RMSE가 설정된 최대값을 초과함"),
        ("Independent surface and 3D-edge evidence", "독립 표면 및 3D 엣지 증거"),
        ("Raw evidence meets both authored limits", "원시 증거가 두 설정 한계를 모두 충족함"),
        ("Pose search rejected the input", "포즈 검색이 입력을 거부함"),
        ("Coverage is below the authored minimum", "커버리지가 설정된 최소값보다 낮음"),
        ("Inlier RMSE is unavailable", "인라이어 RMSE를 사용할 수 없음"),
        ("Inlier RMSE exceeds the authored maximum", "인라이어 RMSE가 설정된 최대값을 초과함"),
        ("Display-only raw evidence", "표시 전용 원시 증거"),
        ("Surface >= ", "표면 >= "),
        (" | Edge >= ", " | 엣지 >= "),
        ("Coverage >= ", "커버리지 >= "),
        ("Acceptance limits not supplied", "판정 한계가 제공되지 않음"),
        (" stages · ", " 단계 · "),
        ("Runtime not supplied", "실행 시간이 제공되지 않음"),
        ("Independent surface + edge limits · no weighted score", "독립 표면 + 엣지 한계 · 가중 점수 없음"),
        ("Edge diagnostic only · no Pass/Fail decision", "엣지 진단 전용 · 통과/실패 판정 없음"),
        ("Decision uses surface limits · edge diagnostic only", "판정은 표면 한계 사용 · 엣지 진단 전용"),
        ("View only · no Pass/Fail decision", "표시 전용 · 통과/실패 판정 없음"),
        ("Decision uses separate authored limits · raw score unchanged", "판정은 별도 설정 한계 사용 · 원시 점수 유지"),
        ("Model edge ", "모델 에지 "),
        (" · scene step ", " · 장면 단계 "),
        (" · facing ", " · 정면 "),
        (" · away ", " · 반대 "),
        (" · grazing ", " · 스침 "),
        (" · declared normals · ", " · 선언된 법선 · "),
        ("acquisition direction unavailable", "취득 방향 사용 불가"),
        ("Edge directions unavailable", "에지 방향 사용 불가"),
        ("Thickness ROI teaching: click one C3D grid location.", "두께 ROI 티칭: C3D 그리드 위치 하나를 클릭하세요."),
        ("Thickness ROI teaching: click the C3D surface to place the ROI", "두께 ROI 티칭: C3D 표면을 클릭해 ROI를 배치하세요"),
        ("Thickness ROI teaching requires C3D grid dimensions", "두께 ROI 티칭에는 C3D 그리드 크기가 필요합니다"),
        ("Thickness ROI changed; run Preview Thickness again", "두께 ROI 변경됨; 두께 미리보기를 다시 실행하세요"),
        ("Thickness ROI taught; configure limits and run Preview Thickness", "두께 ROI 티칭 완료; 한계를 설정하고 두께 미리보기를 실행하세요"),
        ("Current grid ROI row ", "현재 그리드 ROI 행 "),
        ("Grid ROI row ", "그리드 ROI 행 "),
        ("Anchor cell (", "앵커 셀 ("),
        (" | below ", " | 하한 미만 "),
        (", above ", ", 상한 초과 "),
        (" | limits [", " | 한계 ["),
        (" | package ", " | 패키지 "),
        ("declared scalar, uncalibrated", "선언된 스칼라, 보정되지 않음"),
        ("Declared scalar raw-height only; calibration is not inferred.", "선언된 스칼라 원시 높이만 사용; 보정은 추론하지 않음."),
        ("Thickness ROI teaching:", "두께 ROI 티칭:"),
        ("Thickness ROI taught:", "두께 ROI 티칭 완료:"),
        ("Thickness:", "두께:"),
        ("Point pair dimensions:", "포인트 쌍 치수:"),
        ("Point pair:", "포인트 쌍:"),
        ("Select two C3D points and run Preview Dimensions.", "C3D 포인트 두 개를 선택하고 치수 미리보기를 실행하세요."),
        ("Refs ", "참조 "),
        ("Expected D ", "기준 D "),
        (" deg", " 도"),
        ("Gap / Flush:", "갭 / 플러시:"),
        ("Signed left-right ROI edges", "부호 있는 좌우 ROI 에지"),
        ("model dY", "모델 dY"),
        ("expected gap", "기준 갭"),
        (", flush ", ", 플러시 "),
        ("Two recipe-owned C3D regions are required.", "레시피가 소유한 C3D 영역 두 개가 필요합니다."),
        ("Volume:", "체적:"),
        ("Above ", "상부 "),
        (", below ", ", 하부 "),
        (" | expected ", " | 기준 "),
        (" | reference ", " | 참조 "),
        (", measured ", ", 측정 "),
        ("Reference ROI plane and measurement ROI are required.", "참조 ROI 평면과 측정 ROI가 필요합니다."),
        ("Cross-section:", "단면:"),
        (" | valid ", " | 유효 "),
        (" | raw ", " | 원시 "),
        ("An exact C3D row and inclusive column range are required.", "정확한 C3D 행과 포함 열 범위가 필요합니다."),
        ("Flatness:", "평탄도:"),
        ("Reference ROI did not produce a valid fitted plane.", "참조 ROI에서 유효한 피팅 평면을 생성하지 못했습니다."),
        ("Reference ROI and signed surface deviation: pending", "참조 ROI 및 부호 있는 표면 편차: 대기"),
        ("Transform T(", "변환 T("),
        ("Thickness grid ROI row ", "두께 그리드 ROI 행 "),
        ("Warpage best-fit ROI row ", "워페이지 최적 피팅 ROI 행 "),
        ("Reference ROI (", "참조 ROI ("),
        (") half (", ") 반치수 ("),
        ("Point pair ", "포인트 쌍 "),
        ("Volume reference (", "체적 참조 ("),
        ("); measurement (", "); 측정 ("),
        ("Cross-section row ", "단면 행 "),
        (", column ", ", 열 "),
        ("row ", "행 "),
        ("column ", "열 "),
        ("X=column", "X=열"),
        ("Z=row", "Z=행"),
        (", columns ", ", 열 "),
        (", size ", ", 크기 "),
        (", min samples ", ", 최소 샘플 "),
        (", frame ", ", 좌표계 "),
        ("Preview is required", "미리보기가 필요합니다"),
        ("ROI taught; Preview is required.", "ROI 티칭 완료; 미리보기가 필요합니다."),
        ("teach one C3D ROI, then run Preview.", "C3D ROI 하나를 티칭한 후 미리보기를 실행하세요."),
        (" | Pass", " | 통과"),
        (" | Warning", " | 경고"),
        (" | Error", " | 오류"),
        ("within tolerance", "허용오차 이내"),
        ("above tolerance", "허용오차 초과"),
        ("review tolerance", "허용오차 검토"),
        ("invalid result", "잘못된 결과"),
        ("inactive", "비활성"),
        ("Scale: 0 = mean, 1 = peak deviation", "축척: 0 = 평균, 1 = 피크 편차"),
        ("Scale: signed deviation to ROI reference plane", "축척: ROI 기준 평면 대비 부호 있는 편차"),
        ("Scale: mean to peak deviation", "축척: 평균에서 피크 편차"),
        ("Peak: none", "피크: 없음"),
        ("Peak:", "피크:"),
        ("Negative", "음수"),
        ("Positive", "양수"),
        ("Zero", "영점"),
        ("Mean", "평균"),
        ("Tolerance", "허용오차"),
        ("Peak", "피크"),
        ("Point Cloud Height Scale", "포인트 클라우드 높이 축척"),
        ("Low: not loaded", "낮음: 로드되지 않음"),
        ("High: not loaded", "높음: 로드되지 않음"),
        ("Low:", "낮음:"),
        ("High:", "높음:"),
        ("Scale: source Z min to max", "축척: 소스 Z 최소에서 최대"),
        ("Scale: source Z minimum to maximum", "축척: 소스 Z 최소에서 최대"),
        ("range ", "범위 "),
        ("X red", "X 빨강"),
        ("Y green", "Y 초록"),
        ("Z blue", "Z 파랑"),
        ("Identity", "항등"),
        ("unitless", "단위 없음"),
        ("orbit", "회전"),
        ("(none)", "(없음)")
    ];

    public static ViewerLocalization Shared { get; } = new();

    private ViewerLocalization() =>
        OpenVisionLanguageService.LanguageChanged += OnGlobalLanguageChanged;

    public event PropertyChangedEventHandler? PropertyChanged;

    public event EventHandler? LanguageChanged;

    public int Revision { get; private set; }

    public string Resolve(string key, string korean, string english)
    {
        var value = OpenVisionLanguageService.T(key);
        return string.Equals(value, key, StringComparison.Ordinal)
            ? OpenVisionLanguageService.CurrentLanguage == OpenVisionLanguage.English ? english : korean
            : value;
    }

    public string LocalizeRuntimeText(object? value, string? mode = null)
    {
        var text = value?.ToString() ?? string.Empty;
        if (string.Equals(mode, "PointSizeLabel", StringComparison.Ordinal)
            && value is IFormattable formattable)
        {
            text = formattable.ToString("F1", CultureInfo.CurrentCulture) ?? text;
        }

        if (string.Equals(mode, "LineFitPointState", StringComparison.Ordinal)
            && value is bool isInlier)
        {
            text = isInlier ? "Inlier" : "Outlier";
        }

        if (string.Equals(mode, "SurfaceMatchDecision", StringComparison.Ordinal))
        {
            return OpenVisionLanguageService.CurrentLanguage == OpenVisionLanguage.English
                ? text
                : text switch
                {
                    "PASS" => "통과",
                    "FAIL" => "실패",
                    "REJECTED" => "거부됨",
                    "NO DECISION" => "판정 없음",
                    _ => text
                };
        }

        if (OpenVisionLanguageService.CurrentLanguage == OpenVisionLanguage.English)
        {
            return Format(text, mode, "Selection", "Pick");
        }

        var localized = text switch
        {
            "Point" => "포인트",
            "Points" => "포인트",
            "Profile" => "프로파일",
            "Wireframe" => "와이어프레임",
            "Surface" => "표면",
            "Surface + Edges" => "표면 + 엣지",
            "Source" => "소스",
            "Solid" => "단색",
            "Grayscale" => "회색조",
            "Height" => "높이",
            "Intensity" => "강도",
            "Color" => "색상",
            "Depth" => "깊이",
            "Normal" => "노멀",
            "Confidence" => "신뢰도",
            "Signal/Noise" => "신호/잡음",
            "Thermal" => "열화상",
            "Deviation" => "편차",
            "Balanced" => "균형",
            "Detailed" => "상세",
            "Fast" => "빠름",
            "Loaded" => "로드됨",
            "Missing" => "누락됨",
            "Pending" => "대기",
            "Matched" => "일치",
            "Failed" => "실패",
            "ViewerFailed" => "뷰어 실패",
            "Pass" => "통과",
            "Fail" => "실패",
            "Warning" => "경고",
            "Error" => "오류",
            "NotRun" => "미실행",
            "PASS" => "통과",
            "FAIL" => "실패",
            "WARNING" => "경고",
            "ERROR" => "오류",
            "PENDING" => "대기",
            "MATCHED" => "일치",
            "LOADED" => "로드됨",
            "MISSING" => "누락됨",
            "Recipe" => "레시피",
            "Viewer preview" => "뷰어 미리보기",
            "Runner replay" => "Runner 재생",
            "Evidence compare" => "증거 비교",
            "Viewer smoke" => "뷰어 스모크",
            _ => text
        };
        foreach (var (english, korean) in RuntimeReplacements)
        {
            localized = localized.Replace(english, korean, StringComparison.OrdinalIgnoreCase);
        }

        return Format(localized, mode, "선택", "선택점");
    }

    private static string Format(string text, string? mode, string selectionLabel, string pickLabel) =>
        mode switch
        {
            "RenderedC3DPoints" => $"{(selectionLabel == "Selection" ? "Rendered C3D points" : "렌더링된 C3D 포인트")}: {text}",
            "KindLabel" => $"{(selectionLabel == "Selection" ? "Kind" : "종류")}: {text}",
            "VisibleLabel" => $"{(selectionLabel == "Selection" ? "Visible" : "표시")}: {text}",
            "PipelineStepState" => $"{(selectionLabel == "Selection" ? "Pipeline step state" : "파이프라인 단계 상태")}: {text}",
            "StepParameterAdapter" => $"{(selectionLabel == "Selection" ? "Step parameter adapter" : "단계 파라미터 어댑터")}: {text}",
            "AvailableNow" => $"{(selectionLabel == "Selection" ? "Available now" : "현재 사용 가능")}: {text}",
            "Scanline" => $"{(selectionLabel == "Selection" ? "Scanline" : "스캔라인")}: {text}",
            "SchemaLabel" => $"{(selectionLabel == "Selection" ? "Schema" : "스키마")}: {text}",
            "RecipeLabel" => $"{(selectionLabel == "Selection" ? "Recipe" : "레시피")}: {text}",
            "PointsLabel" => $"{(selectionLabel == "Selection" ? "Points" : "포인트")}: {text}",
            "ColorModeLabel" => $"{(selectionLabel == "Selection" ? "Color mode" : "색상 모드")}: {text}",
            "RenderedPointsLabel" => $"{(selectionLabel == "Selection" ? "Rendered points" : "렌더링된 포인트")}: {text}",
            "TrianglesLabel" => $"{(selectionLabel == "Selection" ? "Triangles" : "삼각형")}: {text}",
            "PointSizeLabel" => $"{(selectionLabel == "Selection" ? "Point size" : "포인트 크기")}: {text}px",
            "LineFitPointState" => text,
            "ArtifactNavigatorTitle" => text,
            "ArtifactNavigatorDetail" => text,
            "AddCompatibleTaughtStep" => $"{(selectionLabel == "Selection" ? "Add compatible taught step" : "호환되는 티칭 단계 추가")}: {text}",
            "RuleLabel" => $"{(selectionLabel == "Selection" ? "Rule" : "규칙")}: {text}",
            "Selection" => $"{selectionLabel}: {text}",
            "Pick" => $"{pickLabel}: {text}",
            "Mode" => $"{(selectionLabel == "Selection" ? "Mode" : "모드")}: {text}",
            "Active" => $"{(selectionLabel == "Selection" ? "Active" : "활성")}: {text}",
            _ => text
        };

    private void Refresh()
    {
        Revision++;
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Revision)));
        LanguageChanged?.Invoke(this, EventArgs.Empty);
    }

    private void OnGlobalLanguageChanged(object? sender, EventArgs args) => Refresh();
}
