namespace OpenVisionLab.ThreeD.Viewer.Hosting;

/// <summary>
/// Keeps the public host notification names independent from the concrete
/// ViewModel property names. Unknown notifications intentionally do not leak
/// through the host contract.
/// </summary>
internal static class ViewerHostStatePropertyMap
{
    public static string? Map(string? viewModelPropertyName) => viewModelPropertyName switch
    {
        "C3DSampleVisible" => nameof(ViewerHostState.C3DSampleVisible),
        "GlbSampleVisible" => nameof(ViewerHostState.GlbSampleVisible),
        "LazSampleVisible" => nameof(ViewerHostState.LazSampleVisible),
        "SelectedEntity" => nameof(ViewerHostState.ActiveEntity),
        "SelectedSelectionMode" => nameof(ViewerHostState.SelectionMode),
        "SelectionSummary" => nameof(ViewerHostState.Selection),
        "SelectionOverlayVisible" => nameof(ViewerHostState.SelectionOverlayVisible),
        "NominalActualInput" => nameof(ViewerHostState.HasNominalActualInput),
        "NominalActual.State" => nameof(ViewerHostState.NominalActualState),
        "NominalActual.InputsReady" => nameof(ViewerHostState.NominalActualDisplay),
        "NominalActual.EvidenceSummary" => nameof(ViewerHostState.NominalActualDisplay),
        "NominalActual.StateSummary" => nameof(ViewerHostState.NominalActualDisplay),
        "NominalActual.DirectionSummary" => nameof(ViewerHostState.NominalActualDisplay),
        "NominalActual.CurrentDisplaySamplingSummary" => nameof(ViewerHostState.NominalActualDisplay),
        "NominalActual.NextPreviewSamplingSummary" => nameof(ViewerHostState.NominalActualDisplay),
        "NominalActual.DisplaySamplingChangePending" => nameof(ViewerHostState.NominalActualDisplay),
        "NominalActual.ProgressPercent" => nameof(ViewerHostState.NominalActualDisplay),
        "NominalActual.DistributionVisible" => nameof(ViewerHostState.NominalActualDisplay),
        "NominalActual.DistributionSummary" => nameof(ViewerHostState.NominalActualDisplay),
        "ThicknessVisible" => nameof(ViewerHostState.ThicknessEvidence),
        "ThicknessSummary" => nameof(ViewerHostState.ThicknessEvidence),
        "ThicknessDetails" => nameof(ViewerHostState.ThicknessEvidence),
        "ThicknessMean" => nameof(ViewerHostState.ThicknessEvidence),
        "ThicknessMinimumMeasured" => nameof(ViewerHostState.ThicknessEvidence),
        "ThicknessMaximumMeasured" => nameof(ViewerHostState.ThicknessEvidence),
        "ThicknessRange" => nameof(ViewerHostState.ThicknessEvidence),
        "ThicknessValidSampleCount" => nameof(ViewerHostState.ThicknessEvidence),
        "ProfileVisible" => nameof(ViewerHostState.Profile),
        "ProfileSummary" => nameof(ViewerHostState.Profile),
        "ProfileEndpointSummary" => nameof(ViewerHostState.Profile),
        "ProfileRange" => nameof(ViewerHostState.Profile),
        "ProfilePathData" => nameof(ViewerHostState.Profile),
        "ProfileValidSampleCount" => nameof(ViewerHostState.Profile),
        "ProfileMissingSampleCount" => nameof(ViewerHostState.Profile),
        "ProfileLinkedCursorVisible" => nameof(ViewerHostState.Profile),
        "ProfileLinkedCursorX" => nameof(ViewerHostState.Profile),
        "ProfileLinkedCursorY" => nameof(ViewerHostState.Profile),
        "ProfileLinkedCursorMarkerLeft" => nameof(ViewerHostState.Profile),
        "ProfileLinkedCursorMarkerTop" => nameof(ViewerHostState.Profile),
        "ProfileLinkedCursorSummary" => nameof(ViewerHostState.Profile),
        "SectionProfileVisible" => nameof(ViewerHostState.SectionProfile),
        "SectionProfileSampleCount" => nameof(ViewerHostState.SectionProfile),
        "SectionProfileSummary" => nameof(ViewerHostState.SectionProfile),
        "SectionProfileRange" => nameof(ViewerHostState.SectionProfile),
        "SectionProfilePathData" => nameof(ViewerHostState.SectionProfile),
        "LazSampleName" => nameof(ViewerHostState.SourceSamples),
        "LazSampleSummary" => nameof(ViewerHostState.SourceSamples),
        "GlbSampleName" => nameof(ViewerHostState.SourceSamples),
        "GlbSampleSummary" => nameof(ViewerHostState.SourceSamples),
        "SceneContractSummary" => nameof(ViewerHostState.SceneDisplay),
        "TransformSummary" => nameof(ViewerHostState.SceneDisplay),
        "AlignmentSummary" => nameof(ViewerHostState.SceneDisplay),
        "CoordinateMappingSummary" => nameof(ViewerHostState.SceneDisplay),
        "C3DSamplePointCount" => nameof(ViewerHostState.SceneDisplay),
        "LazSamplingSummary" => nameof(ViewerHostState.SceneDisplay),
        "EntityLayers" => nameof(ViewerHostState.EntityLayers),
        "HudDetailsVisible" => nameof(ViewerHostState.Presentation),
        "ColorModes" => nameof(ViewerHostState.Presentation),
        "SelectedColorMode" => nameof(ViewerHostState.Presentation),
        "DisplaySettingsRevision" => nameof(ViewerHostState.Presentation),
        "MeasurementVisible" => nameof(ViewerHostState.Presentation),
        "ResultOverlayVisible" => nameof(ViewerHostState.Presentation),
        "C3DHeightDistributionVisible" => nameof(ViewerHostState.Presentation),
        "C3DHeightDistributionSourceSha256" => nameof(ViewerHostState.Presentation),
        "C3DHeightColorMinimumRaw" => nameof(ViewerHostState.Presentation),
        "C3DHeightColorMaximumRaw" => nameof(ViewerHostState.Presentation),
        "C3DHeightColorRangeAuto" => nameof(ViewerHostState.Presentation),
        "C3DHeightColorRangeRevision" => nameof(ViewerHostState.Presentation),
        "C3DHeightColorRangeSummary" => nameof(ViewerHostState.Presentation),
        "PreviewToolResult" => nameof(ViewerHostState.Inspection),
        "ResultEntities" => nameof(ViewerHostState.Inspection),
        "ProjectionMode" => nameof(ViewerHostState.Inspection),
        "IsTopOrthographicView" => nameof(ViewerHostState.Inspection),
        "IsPerspectiveView" => nameof(ViewerHostState.Inspection),
        "PickCoordinate" => nameof(ViewerHostState.PickCoordinate),
        "MeasurementSummary" => nameof(ViewerHostState.MeasurementSummary),
        "ResultSummary" => nameof(ViewerHostState.ResultSummary),
        "RecipeSummary" => nameof(ViewerHostState.RecipeSummary),
        "ViewerStatus" => nameof(ViewerHostState.ViewerStatus),
        _ => null
    };
}
